[tool.poetry]
name = "mlflow-for-ml-deployment"
version = "0.1.0"
description = ""
authors = ["Manuel Gil <manuelgilsitio@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "batch_inference", format = ["sdist", "wheel"] },
    { include = "utils", format = ["sdist", "wheel"] },
]
[tool.poetry.dependencies]
python = "^3.11"
mlflow = "^2.22.0"
scikit-learn = "^1.6.1"
ipython = "^9.2.0"
notebook = "^7.4.1"

[tool.poetry.scripts]
iris_clf_train ="batch_inference.iris_classifier.train:main"
iris_clf_inference = "batch_inference.iris_classifier.inference:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
